version: "3"
services:
  dnsmasq-api:
    container_name: dnsmasq-api
    image: dnsmasq-api:latest
    ports:
      - "<external IP>:<port>:5000/tcp"
    environment:
      TZ: 'UTC'
      MATCH_NETWORKS: "192.168.0.0/24 192.168.1.0/24 192.168.2.0/24"
    volumes:
      - "/path/tp/dnsmasq.leases:/data/dnsmasq.leases:ro"     
    restart: unless-stopped
    networks:
      dnsmasq-br:

networks:
  dnsmasq-br:
    driver: bridge