version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "8128:80/tcp"
    environment:
      TZ: 'UTC'
      # see the github link above for info about these settings
      # WEBPASSWORD: 'set a secure password here or it will be random'
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1'
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'         
    restart: unless-stopped
    networks:
      vpcbr:
        ipv4_address: 10.55.55.2

  # squid container: https://hub.docker.com/r/ubuntu/squid  
  squid:
    container_name: squid
    image: ubuntu/squid:latest
    # image: squid-alpine:latest
    ports:
      - "3128:3128/tcp"
    environment:
      TZ: 'UTC'
    volumes:
      - './etc-squid/squid.conf:/etc/squid/squid.conf'
    restart: unless-stopped
    networks:
      vpcbr:
        ipv4_address: 10.55.55.3

networks:
  vpcbr:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.55.55.0/29
