FROM centos:8
RUN dnf install -y skopeo \
  && dnf clean all

# CA cert
RUN curl -o /etc/pki/ca-trust/source/anchors/home_CA.crt \
  http://nfs1.home.lan/minio/software/home_CA/home_CA.crt \
  && update-ca-trust

CMD ["--help"]
ENTRYPOINT ["/usr/bin/skopeo"]
