FROM centos:8
RUN dnf install -y skopeo \
  && dnf clean all

# CA certs - copy file and update cert DB
COPY *.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates

CMD ["--help"]
ENTRYPOINT ["/usr/bin/skopeo"]
